// 고객페이지에서 담당자가 관리하는 추천 목록. 기존 Firestore 목록과 섞지 않는다.
export const clientpageClients = {
  '보울게임즈': 'bowlgames',
  '담은결': 'dameungyeol',
  '위프코리아': 'whiffkorea',
  '웰던프로덕트': 'welldoneproduct',
  '사유존': 'sayuzone',
  '서윤웰스': 'sywells',
  '동선컴퍼니': 'dongseoncompany',
  '새움솔루션': 'saeumsolution',
  '트리봇코리아': 'tribotkorea',
  '프리랜드': 'freeland',
  '처음청약': 'firstsubscription',
  '프로젝트모름': 'projectmoreum',
  '잘빠진방앗간': 'jalppajinbangatgan',
  '비쉐어': 'beshare',
  '디지털이엔에스': 'digitalens',
  '영원희': 'youngwonhee',
  '모비먼트': 'mobiment',
};
